language: python

python:
  - "3.6"
  - "3.8"

# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install codecov

# command to run tests
script:
  - coverage run -m unittest discover -s tests/

after_success:
  - codecov
